apiVersion: v1 
kind: Pod 
metadata:
  name: my-pod 
spec:
  containers:
  - name: gradle
    image: gradle:6.4.1-jdk11 
    command: 
    - tail 
    args:
    - -f
    - /dev/null
    securityContext:
      privileged: true 
    lifecycle:
      postStart:
        exec:
          command: ["/bin/sh", "-c", "apt-get update && apt-get install -y git dos2unix"]
  - name: docker 
    image: docker:dind 
    command:
    - tail 
    args:
    - -f
    - /dev/null 
    volumeMounts:
    - name: docker-sock 
      mountPath: /var/run/docker.sock
    securityContext:
      privileged: true
  volumes:
  - name: docker-sock 
    hostPath:
      path: /var/run/docker.sock
